### ISSUE TITLE
BUG - Wearing any Backpack renders you Overt

### ISSUE THREAD

**Issue by mrschick** [SpicyBagpipes/KJW_Imposters#5]
Yesterday I noticed that backpacks with `KJW_Imposters_SuspicionAmount = 0`, like "Everyday Backpack (Black)" (`B_CivilianBackpack_01_Base_F`), render an otherwise "incognito" wearer completely overt.

**Repro Steps:**
- Use the default CBA Settings of this mod.
- Only wear civilian clothing, like `[[[],[],[],["U_C_Man_casual_1_F",[]],[],["B_CivilianBackpack_01_Everyday_Black_F",[]],"H_Cap_red","",[],["","","","","",""]],[["ace_arsenal_face","WhiteHead_06"]]]` (Pastable into ACE Arsenal).
- You will then always be overt while wearing the backpack, while taking it off will render you covert.
This applies to all "civilian" vanilla and modded (RHS/3CB) backpacks that I have come across, despite all of them having "Susness" 0 in the arsenal and Compats.

I identified the cause as 584675d90ac5f58d59a996b10f984d1f2e5d6350.
The changes applied by that commit lead to backpacks like `B_CivilianBackpack_01_Everyday_Black_F` to not be added to `kjw_imposters_core_itemScores`, which then causes the following line to default to them being fully-overt equipment, with `SuspicionAmount = 1`.
https://github.com/SpicyBagpipes/KJW_Imposters/blob/b26ebc907b047303f05aa37f46f9338776ccf087/addons/core/functions/fnc_processUnit.sqf#L36

**Comment by SpicyBagpipes** [comment]
Thanks for this, I'll get around to solving it soon - my group plays without backpack processing on so didn't notice!

**Comment by SpicyBagpipes** [comment]
Fixed in b2e360e, will publish on Monday

**Comment by mrschick** [comment]
Excellent, thanks for the quick fix 🤙🏻

**Comment by mrschick** [comment]
This appears to still be an issue with 3CB backpacks like `UK3CB_B_Hiker` and `UK3CB_CW_SOV_O_EARLY_B_RIF` (inherits susness from `UK3CB_B_Fieldpack`, which has the same issue).
They both have Susness 0 in the arsenal but are not loaded to `kjw_imposters_core_itemScores`.

**Comment by SpicyBagpipes** [comment]
> This appears to still be an issue with 3CB backpacks like `UK3CB_B_Hiker` and `UK3CB_CW_SOV_O_EARLY_B_RIF` (inherits susness from `UK3CB_B_Fieldpack`, which has the same issue). They both have Susness 0 in the arsenal but are not loaded to `kjw_imposters_core_itemScores`.

Just took a look, it's due to them not having 901 (backpack slot) in their `allowedSlots[]`... They have 1000 instead which is peculiar to say the least. I'll add a check for `isBackpack = 1` as an alternative to the condition

**Comment by SpicyBagpipes** [comment]
Hopefully fixed in 3331179 - testing showed it collected now, will update on Monday and let me know if you still have this issue.

**Comment by SpicyBagpipes** [comment]
This fix was not published on Monday as I forgot, my bad. Will do it next Monday - don't want to do an update so close to weekend given hemtt regenerates bikeys

**Comment by SpicyBagpipes** [comment]
Fix published, let me know if there's any further issues with it, else close this issue yourself :)

**Comment by mrschick** [comment]
Double checked it with all backpacks of RHS + Project OPFOR + 3CB Factions that inherit Susness 0, none present the issue.
As far as I'm concerned, this is resolved 👌🏻
