### ISSUE TITLE
BUG - Manning and firing from military vehicles won't render you overt

### ISSUE THREAD

**Issue by mrschick** [SpicyBagpipes/KJW_Imposters#6]
Noticing some really odd behaviour with military vehicles on the latest public release, such as manning and firing from Tanks/APCs not rendering one overt.

**Repro steps:**
- Be covert (civilian attire, holstered pistol);
- Get into a Merkava (M2 Slammer) Tank;
- You'll remain covert even while firing at hostiles, with the "covert bar" UI flickering every few seconds between invisible and fully green;

Teleporting right into the vehicle via Zeus does appear to render oneself overt and add susPoints.

**Comment by SpicyBagpipes** [comment]
will investigate next week, have seen the covert bar flickering before but couldnt figure out why

**Comment by SpicyBagpipes** [comment]
Fixed in 853f7c2, please test locally and confirm it works due to not getting the covert bar flickering in my testing

**Comment by mrschick** [comment]
Did you include the fix in yesterday's update? I don't see it in the changelog.

**Comment by SpicyBagpipes** [comment]
I did not as was expecting it to take longer

**Comment by mrschick** [comment]
Copy. Tested latest changes locally, susPoint increase works well, GUI still flickers, going to investigate that.

**Comment by mrschick** [comment]
Couldn't reproduce the GUI flickering anymore, might open a fresh issue if it happens again.
Either way, the main issue is resolved 🤙🏻
